# Generated by Django 3.2.16 on 2023-01-13 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('date_time', models.DateTimeField()),
                ('stop_loss', models.IntegerField(max_length=10)),
                ('take_profit', models.IntegerField(max_length=3)),
                ('initial_price', models.IntegerField(max_length=10)),
                ('closing_price', models.IntegerField(blank=True, max_length=10)),
                ('title', models.CharField(default='<django.db.models.fields.CharField> order created on <django.db.models.fields.DateTimeField>', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
