# Generated by Django 3.2.16 on 2023-01-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='leverage',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='closing_price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='initial_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='stop_loss',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='take_profit',
            field=models.IntegerField(),
        ),
    ]
