# Generated by Django 3.2.16 on 2023-01-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230113_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='closing_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
