# Generated by Django 3.2.16 on 2023-01-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_closing_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_time',
            new_name='start_date_time',
        ),
        migrations.AddField(
            model_name='order',
            name='close_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
