# Generated by Django 3.2.16 on 2023-01-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230113_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='closing_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='initial_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='stop_loss',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='take_profit',
            field=models.FloatField(),
        ),
    ]
