# Generated by Django 3.2.16 on 2023-01-20 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230120_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='close',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='datetime_id',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='high',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='low',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='open',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='volume',
        ),
    ]
