# Generated by Django 3.2.16 on 2023-01-20 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230120_2313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crypto',
        ),
    ]
