# Generated by Django 3.2.16 on 2023-01-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_crypto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crypto',
            old_name='datetime_id',
            new_name='datetime',
        ),
        migrations.AlterField(
            model_name='crypto',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
