# Generated by Django 3.2.16 on 2023-01-20 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230120_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crypto',
        ),
    ]
