# Generated by Django 3.2.16 on 2023-01-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
