# Generated by Django 3.2.16 on 2023-01-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_crypto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
