# Generated by Django 3.2.16 on 2023-01-20 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_crypto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crypto',
            old_name='datetime',
            new_name='date_and_time',
        ),
    ]
