# Generated by Django 3.2.16 on 2023-01-21 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_datetime_crypto_date_and_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crypto',
            options={'ordering': ('date_and_time',)},
        ),
    ]
