# Generated by Django 3.2.16 on 2023-01-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_crypto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(default='<bound method Field.value_to_string of <django.db.models.fields.CharField>> order created on <bound method DateTimeField.value_to_string of <django.db.models.fields.DateTimeField>>', max_length=255),
        ),
    ]
